#!/usr/bin/python
#
# print defines from common.pyc
#
from common import *

print 'USER_DL_DIR == %s' % USER_DL_DIR
print 'EXPIRED_TORRENT_DIR == %s' % EXPIRED_TORRENT_DIR
print 'MAX_SLEEP_TIME == %s' % MAX_SLEEP_TIME
print 'FILE_DELIMITER == %s' % FILE_DELIMITER
print 'PERCENT_KEEP_FREE == %s' % PERCENT_KEEP_FREE
print 'MASTER_HASH_LIST == %s' % MASTER_HASH_LIST
print 'INCOMING_TORRENT_DIR == %s' % INCOMING_TORRENT_DIR
print 'COMPLETED_TORRENT_DIR == %s' % COMPLETED_TORRENT_DIR
print 'TORRENT_XML == %s' % TORRENT_XML
print 'AUTOSTOPD_DIR == %s' % AUTOSTOPD_DIR
print 'ACTIVE_USER_TORRENTS == %s' % ACTIVE_USER_TORRENTS
